// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: locatorservices.proto

package grpc.locator;

public interface LocateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:locatorservices.LocateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string address = 2;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
