// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataservices.proto

package grpc.data;

public final class DataServicesProto {
  private DataServicesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_PutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_PutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_PutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_PutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_DeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_MigrateSlice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_MigrateSlice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_MigrateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_MigrateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_MigrateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_MigrateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_TransferDataFromRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_TransferDataFromRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_TransferDataFromResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_TransferDataFromResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_TransferDataToRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_TransferDataToRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_TransferDataToResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_TransferDataToResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_Slot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_Slot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_TryPutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_TryPutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_TryDeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_TryDeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_SyncRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_SyncRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_SyncResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_SyncResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataservices_SyncSeq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataservices_SyncSeq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022dataservices.proto\022\014dataservices\"(\n\nPu" +
      "tRequest\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\035\n\013" +
      "PutResponse\022\016\n\006status\030\001 \001(\005\"\031\n\nGetReques" +
      "t\022\013\n\003key\030\001 \001(\t\",\n\013GetResponse\022\016\n\006status\030" +
      "\001 \001(\005\022\r\n\005value\030\002 \001(\t\"\034\n\rDeleteRequest\022\013\n" +
      "\003key\030\001 \001(\t\" \n\016DeleteResponse\022\016\n\006status\030\001" +
      " \001(\005\"0\n\014MigrateSlice\022\017\n\007address\030\001 \001(\t\022\017\n" +
      "\007slot_id\030\002 \003(\005\"D\n\016MigrateRequest\0222\n\016migr" +
      "ate_slices\030\001 \003(\0132\032.dataservices.MigrateS" +
      "lice\"!\n\017MigrateResponse\022\016\n\006status\030\001 \001(\005\"" +
      "#\n\005Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"*\n\027" +
      "TransferDataFromRequest\022\017\n\007slot_id\030\001 \003(\005" +
      "\"@\n\030TransferDataFromResponse\022$\n\007entries\030" +
      "\001 \003(\0132\023.dataservices.Entry\"=\n\025TransferDa" +
      "taToRequest\022$\n\007entries\030\001 \003(\0132\023.dataservi" +
      "ces.Entry\"(\n\026TransferDataToResponse\022\016\n\006s" +
      "tatus\030\001 \001(\005\"=\n\004Slot\022\017\n\007slot_id\030\001 \001(\005\022$\n\007" +
      "entries\030\002 \003(\0132\023.dataservices.Entry\"=\n\rTr" +
      "yPutRequest\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022" +
      "\020\n\010sync_seq\030\003 \001(\005\"@\n\020TryDeleteRequest\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022\020\n\010sync_seq\030\003 " +
      "\001(\005\"\035\n\013SyncRequest\022\016\n\006status\030\001 \001(\005\"1\n\014Sy" +
      "ncResponse\022!\n\005slots\030\001 \003(\0132\022.dataservices" +
      ".Slot\"\033\n\007SyncSeq\022\020\n\010sync_seq\030\001 \001(\0052\263\007\n\014D" +
      "ataServices\022<\n\003Put\022\030.dataservices.PutReq" +
      "uest\032\031.dataservices.PutResponse\"\000\022<\n\003Get" +
      "\022\030.dataservices.GetRequest\032\031.dataservice" +
      "s.GetResponse\"\000\022E\n\006Delete\022\033.dataservices" +
      ".DeleteRequest\032\034.dataservices.DeleteResp" +
      "onse\"\000\022L\n\013MigrateFrom\022\034.dataservices.Mig" +
      "rateRequest\032\035.dataservices.MigrateRespon" +
      "se\"\000\022J\n\tMigrateTo\022\034.dataservices.Migrate" +
      "Request\032\035.dataservices.MigrateResponse\"\000" +
      "\022c\n\020TransferDataFrom\022%.dataservices.Tran" +
      "sferDataFromRequest\032&.dataservices.Trans" +
      "ferDataFromResponse\"\000\022]\n\016TransferDataTo\022" +
      "#.dataservices.TransferDataToRequest\032$.d" +
      "ataservices.TransferDataToResponse\"\000\022?\n\004" +
      "Sync\022\031.dataservices.SyncRequest\032\032.datase" +
      "rvices.SyncResponse\"\000\022B\n\006TryPut\022\033.datase" +
      "rvices.TryPutRequest\032\031.dataservices.PutR" +
      "esponse\"\000\022K\n\tTryDelete\022\036.dataservices.Tr" +
      "yDeleteRequest\032\034.dataservices.DeleteResp" +
      "onse\"\000\0228\n\006Commit\022\025.dataservices.SyncSeq\032" +
      "\025.dataservices.SyncSeq\"\000\022:\n\010RollBack\022\025.d" +
      "ataservices.SyncSeq\032\025.dataservices.SyncS" +
      "eq\"\000\022:\n\010CheckLog\022\025.dataservices.SyncSeq\032" +
      "\025.dataservices.SyncSeq\"\000B&\n\tgrpc.dataB\021D" +
      "ataServicesProtoP\001\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dataservices_PutRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dataservices_PutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_PutRequest_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_dataservices_PutResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dataservices_PutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_PutResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_dataservices_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dataservices_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_GetRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_dataservices_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_dataservices_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_GetResponse_descriptor,
        new java.lang.String[] { "Status", "Value", });
    internal_static_dataservices_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_dataservices_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_DeleteRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_dataservices_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_dataservices_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_DeleteResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_dataservices_MigrateSlice_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_dataservices_MigrateSlice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_MigrateSlice_descriptor,
        new java.lang.String[] { "Address", "SlotId", });
    internal_static_dataservices_MigrateRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_dataservices_MigrateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_MigrateRequest_descriptor,
        new java.lang.String[] { "MigrateSlices", });
    internal_static_dataservices_MigrateResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_dataservices_MigrateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_MigrateResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_dataservices_Entry_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_dataservices_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_Entry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_dataservices_TransferDataFromRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_dataservices_TransferDataFromRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_TransferDataFromRequest_descriptor,
        new java.lang.String[] { "SlotId", });
    internal_static_dataservices_TransferDataFromResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_dataservices_TransferDataFromResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_TransferDataFromResponse_descriptor,
        new java.lang.String[] { "Entries", });
    internal_static_dataservices_TransferDataToRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_dataservices_TransferDataToRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_TransferDataToRequest_descriptor,
        new java.lang.String[] { "Entries", });
    internal_static_dataservices_TransferDataToResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_dataservices_TransferDataToResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_TransferDataToResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_dataservices_Slot_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_dataservices_Slot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_Slot_descriptor,
        new java.lang.String[] { "SlotId", "Entries", });
    internal_static_dataservices_TryPutRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_dataservices_TryPutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_TryPutRequest_descriptor,
        new java.lang.String[] { "Key", "Value", "SyncSeq", });
    internal_static_dataservices_TryDeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_dataservices_TryDeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_TryDeleteRequest_descriptor,
        new java.lang.String[] { "Key", "Value", "SyncSeq", });
    internal_static_dataservices_SyncRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_dataservices_SyncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_SyncRequest_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_dataservices_SyncResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_dataservices_SyncResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_SyncResponse_descriptor,
        new java.lang.String[] { "Slots", });
    internal_static_dataservices_SyncSeq_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_dataservices_SyncSeq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataservices_SyncSeq_descriptor,
        new java.lang.String[] { "SyncSeq", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
