// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataservices.proto

package grpc.data;

public interface MigrateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataservices.MigrateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
   */
  java.util.List<grpc.data.MigrateSlice> 
      getMigrateSlicesList();
  /**
   * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
   */
  grpc.data.MigrateSlice getMigrateSlices(int index);
  /**
   * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
   */
  int getMigrateSlicesCount();
  /**
   * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
   */
  java.util.List<? extends grpc.data.MigrateSliceOrBuilder> 
      getMigrateSlicesOrBuilderList();
  /**
   * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
   */
  grpc.data.MigrateSliceOrBuilder getMigrateSlicesOrBuilder(
      int index);
}
