// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataservices.proto

package grpc.data;

/**
 * Protobuf type {@code dataservices.MigrateRequest}
 */
public final class MigrateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dataservices.MigrateRequest)
    MigrateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MigrateRequest.newBuilder() to construct.
  private MigrateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MigrateRequest() {
    migrateSlices_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MigrateRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MigrateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              migrateSlices_ = new java.util.ArrayList<grpc.data.MigrateSlice>();
              mutable_bitField0_ |= 0x00000001;
            }
            migrateSlices_.add(
                input.readMessage(grpc.data.MigrateSlice.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        migrateSlices_ = java.util.Collections.unmodifiableList(migrateSlices_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.data.DataServicesProto.internal_static_dataservices_MigrateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.data.DataServicesProto.internal_static_dataservices_MigrateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.data.MigrateRequest.class, grpc.data.MigrateRequest.Builder.class);
  }

  public static final int MIGRATE_SLICES_FIELD_NUMBER = 1;
  private java.util.List<grpc.data.MigrateSlice> migrateSlices_;
  /**
   * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.data.MigrateSlice> getMigrateSlicesList() {
    return migrateSlices_;
  }
  /**
   * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.data.MigrateSliceOrBuilder> 
      getMigrateSlicesOrBuilderList() {
    return migrateSlices_;
  }
  /**
   * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
   */
  @java.lang.Override
  public int getMigrateSlicesCount() {
    return migrateSlices_.size();
  }
  /**
   * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
   */
  @java.lang.Override
  public grpc.data.MigrateSlice getMigrateSlices(int index) {
    return migrateSlices_.get(index);
  }
  /**
   * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
   */
  @java.lang.Override
  public grpc.data.MigrateSliceOrBuilder getMigrateSlicesOrBuilder(
      int index) {
    return migrateSlices_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < migrateSlices_.size(); i++) {
      output.writeMessage(1, migrateSlices_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < migrateSlices_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, migrateSlices_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.data.MigrateRequest)) {
      return super.equals(obj);
    }
    grpc.data.MigrateRequest other = (grpc.data.MigrateRequest) obj;

    if (!getMigrateSlicesList()
        .equals(other.getMigrateSlicesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMigrateSlicesCount() > 0) {
      hash = (37 * hash) + MIGRATE_SLICES_FIELD_NUMBER;
      hash = (53 * hash) + getMigrateSlicesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.data.MigrateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.data.MigrateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.data.MigrateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.data.MigrateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.data.MigrateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.data.MigrateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.data.MigrateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.data.MigrateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.data.MigrateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.data.MigrateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.data.MigrateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.data.MigrateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.data.MigrateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dataservices.MigrateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dataservices.MigrateRequest)
      grpc.data.MigrateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.data.DataServicesProto.internal_static_dataservices_MigrateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.data.DataServicesProto.internal_static_dataservices_MigrateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.data.MigrateRequest.class, grpc.data.MigrateRequest.Builder.class);
    }

    // Construct using grpc.data.MigrateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMigrateSlicesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (migrateSlicesBuilder_ == null) {
        migrateSlices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        migrateSlicesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.data.DataServicesProto.internal_static_dataservices_MigrateRequest_descriptor;
    }

    @java.lang.Override
    public grpc.data.MigrateRequest getDefaultInstanceForType() {
      return grpc.data.MigrateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.data.MigrateRequest build() {
      grpc.data.MigrateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.data.MigrateRequest buildPartial() {
      grpc.data.MigrateRequest result = new grpc.data.MigrateRequest(this);
      int from_bitField0_ = bitField0_;
      if (migrateSlicesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          migrateSlices_ = java.util.Collections.unmodifiableList(migrateSlices_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.migrateSlices_ = migrateSlices_;
      } else {
        result.migrateSlices_ = migrateSlicesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.data.MigrateRequest) {
        return mergeFrom((grpc.data.MigrateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.data.MigrateRequest other) {
      if (other == grpc.data.MigrateRequest.getDefaultInstance()) return this;
      if (migrateSlicesBuilder_ == null) {
        if (!other.migrateSlices_.isEmpty()) {
          if (migrateSlices_.isEmpty()) {
            migrateSlices_ = other.migrateSlices_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMigrateSlicesIsMutable();
            migrateSlices_.addAll(other.migrateSlices_);
          }
          onChanged();
        }
      } else {
        if (!other.migrateSlices_.isEmpty()) {
          if (migrateSlicesBuilder_.isEmpty()) {
            migrateSlicesBuilder_.dispose();
            migrateSlicesBuilder_ = null;
            migrateSlices_ = other.migrateSlices_;
            bitField0_ = (bitField0_ & ~0x00000001);
            migrateSlicesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMigrateSlicesFieldBuilder() : null;
          } else {
            migrateSlicesBuilder_.addAllMessages(other.migrateSlices_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.data.MigrateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.data.MigrateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<grpc.data.MigrateSlice> migrateSlices_ =
      java.util.Collections.emptyList();
    private void ensureMigrateSlicesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        migrateSlices_ = new java.util.ArrayList<grpc.data.MigrateSlice>(migrateSlices_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.data.MigrateSlice, grpc.data.MigrateSlice.Builder, grpc.data.MigrateSliceOrBuilder> migrateSlicesBuilder_;

    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public java.util.List<grpc.data.MigrateSlice> getMigrateSlicesList() {
      if (migrateSlicesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(migrateSlices_);
      } else {
        return migrateSlicesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public int getMigrateSlicesCount() {
      if (migrateSlicesBuilder_ == null) {
        return migrateSlices_.size();
      } else {
        return migrateSlicesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public grpc.data.MigrateSlice getMigrateSlices(int index) {
      if (migrateSlicesBuilder_ == null) {
        return migrateSlices_.get(index);
      } else {
        return migrateSlicesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public Builder setMigrateSlices(
        int index, grpc.data.MigrateSlice value) {
      if (migrateSlicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMigrateSlicesIsMutable();
        migrateSlices_.set(index, value);
        onChanged();
      } else {
        migrateSlicesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public Builder setMigrateSlices(
        int index, grpc.data.MigrateSlice.Builder builderForValue) {
      if (migrateSlicesBuilder_ == null) {
        ensureMigrateSlicesIsMutable();
        migrateSlices_.set(index, builderForValue.build());
        onChanged();
      } else {
        migrateSlicesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public Builder addMigrateSlices(grpc.data.MigrateSlice value) {
      if (migrateSlicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMigrateSlicesIsMutable();
        migrateSlices_.add(value);
        onChanged();
      } else {
        migrateSlicesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public Builder addMigrateSlices(
        int index, grpc.data.MigrateSlice value) {
      if (migrateSlicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMigrateSlicesIsMutable();
        migrateSlices_.add(index, value);
        onChanged();
      } else {
        migrateSlicesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public Builder addMigrateSlices(
        grpc.data.MigrateSlice.Builder builderForValue) {
      if (migrateSlicesBuilder_ == null) {
        ensureMigrateSlicesIsMutable();
        migrateSlices_.add(builderForValue.build());
        onChanged();
      } else {
        migrateSlicesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public Builder addMigrateSlices(
        int index, grpc.data.MigrateSlice.Builder builderForValue) {
      if (migrateSlicesBuilder_ == null) {
        ensureMigrateSlicesIsMutable();
        migrateSlices_.add(index, builderForValue.build());
        onChanged();
      } else {
        migrateSlicesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public Builder addAllMigrateSlices(
        java.lang.Iterable<? extends grpc.data.MigrateSlice> values) {
      if (migrateSlicesBuilder_ == null) {
        ensureMigrateSlicesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, migrateSlices_);
        onChanged();
      } else {
        migrateSlicesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public Builder clearMigrateSlices() {
      if (migrateSlicesBuilder_ == null) {
        migrateSlices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        migrateSlicesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public Builder removeMigrateSlices(int index) {
      if (migrateSlicesBuilder_ == null) {
        ensureMigrateSlicesIsMutable();
        migrateSlices_.remove(index);
        onChanged();
      } else {
        migrateSlicesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public grpc.data.MigrateSlice.Builder getMigrateSlicesBuilder(
        int index) {
      return getMigrateSlicesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public grpc.data.MigrateSliceOrBuilder getMigrateSlicesOrBuilder(
        int index) {
      if (migrateSlicesBuilder_ == null) {
        return migrateSlices_.get(index);  } else {
        return migrateSlicesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public java.util.List<? extends grpc.data.MigrateSliceOrBuilder> 
         getMigrateSlicesOrBuilderList() {
      if (migrateSlicesBuilder_ != null) {
        return migrateSlicesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(migrateSlices_);
      }
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public grpc.data.MigrateSlice.Builder addMigrateSlicesBuilder() {
      return getMigrateSlicesFieldBuilder().addBuilder(
          grpc.data.MigrateSlice.getDefaultInstance());
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public grpc.data.MigrateSlice.Builder addMigrateSlicesBuilder(
        int index) {
      return getMigrateSlicesFieldBuilder().addBuilder(
          index, grpc.data.MigrateSlice.getDefaultInstance());
    }
    /**
     * <code>repeated .dataservices.MigrateSlice migrate_slices = 1;</code>
     */
    public java.util.List<grpc.data.MigrateSlice.Builder> 
         getMigrateSlicesBuilderList() {
      return getMigrateSlicesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.data.MigrateSlice, grpc.data.MigrateSlice.Builder, grpc.data.MigrateSliceOrBuilder> 
        getMigrateSlicesFieldBuilder() {
      if (migrateSlicesBuilder_ == null) {
        migrateSlicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.data.MigrateSlice, grpc.data.MigrateSlice.Builder, grpc.data.MigrateSliceOrBuilder>(
                migrateSlices_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        migrateSlices_ = null;
      }
      return migrateSlicesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dataservices.MigrateRequest)
  }

  // @@protoc_insertion_point(class_scope:dataservices.MigrateRequest)
  private static final grpc.data.MigrateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.data.MigrateRequest();
  }

  public static grpc.data.MigrateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MigrateRequest>
      PARSER = new com.google.protobuf.AbstractParser<MigrateRequest>() {
    @java.lang.Override
    public MigrateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MigrateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MigrateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MigrateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.data.MigrateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

