// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataservices.proto

package grpc.data;

public interface SyncResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataservices.SyncResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .dataservices.Slot slots = 1;</code>
   */
  java.util.List<grpc.data.Slot> 
      getSlotsList();
  /**
   * <code>repeated .dataservices.Slot slots = 1;</code>
   */
  grpc.data.Slot getSlots(int index);
  /**
   * <code>repeated .dataservices.Slot slots = 1;</code>
   */
  int getSlotsCount();
  /**
   * <code>repeated .dataservices.Slot slots = 1;</code>
   */
  java.util.List<? extends grpc.data.SlotOrBuilder> 
      getSlotsOrBuilderList();
  /**
   * <code>repeated .dataservices.Slot slots = 1;</code>
   */
  grpc.data.SlotOrBuilder getSlotsOrBuilder(
      int index);
}
