// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataservices.proto

package grpc.data;

public interface SyncSeqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataservices.SyncSeq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sync_seq = 1;</code>
   * @return The syncSeq.
   */
  int getSyncSeq();
}
