// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataservices.proto

package grpc.data;

/**
 * Protobuf type {@code dataservices.SyncResponse}
 */
public final class SyncResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dataservices.SyncResponse)
    SyncResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SyncResponse.newBuilder() to construct.
  private SyncResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SyncResponse() {
    slots_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SyncResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SyncResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              slots_ = new java.util.ArrayList<grpc.data.Slot>();
              mutable_bitField0_ |= 0x00000001;
            }
            slots_.add(
                input.readMessage(grpc.data.Slot.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        slots_ = java.util.Collections.unmodifiableList(slots_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.data.DataServicesProto.internal_static_dataservices_SyncResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.data.DataServicesProto.internal_static_dataservices_SyncResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.data.SyncResponse.class, grpc.data.SyncResponse.Builder.class);
  }

  public static final int SLOTS_FIELD_NUMBER = 1;
  private java.util.List<grpc.data.Slot> slots_;
  /**
   * <code>repeated .dataservices.Slot slots = 1;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.data.Slot> getSlotsList() {
    return slots_;
  }
  /**
   * <code>repeated .dataservices.Slot slots = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.data.SlotOrBuilder> 
      getSlotsOrBuilderList() {
    return slots_;
  }
  /**
   * <code>repeated .dataservices.Slot slots = 1;</code>
   */
  @java.lang.Override
  public int getSlotsCount() {
    return slots_.size();
  }
  /**
   * <code>repeated .dataservices.Slot slots = 1;</code>
   */
  @java.lang.Override
  public grpc.data.Slot getSlots(int index) {
    return slots_.get(index);
  }
  /**
   * <code>repeated .dataservices.Slot slots = 1;</code>
   */
  @java.lang.Override
  public grpc.data.SlotOrBuilder getSlotsOrBuilder(
      int index) {
    return slots_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < slots_.size(); i++) {
      output.writeMessage(1, slots_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < slots_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, slots_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.data.SyncResponse)) {
      return super.equals(obj);
    }
    grpc.data.SyncResponse other = (grpc.data.SyncResponse) obj;

    if (!getSlotsList()
        .equals(other.getSlotsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSlotsCount() > 0) {
      hash = (37 * hash) + SLOTS_FIELD_NUMBER;
      hash = (53 * hash) + getSlotsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.data.SyncResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.data.SyncResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.data.SyncResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.data.SyncResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.data.SyncResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.data.SyncResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.data.SyncResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.data.SyncResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.data.SyncResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.data.SyncResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.data.SyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.data.SyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.data.SyncResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dataservices.SyncResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dataservices.SyncResponse)
      grpc.data.SyncResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.data.DataServicesProto.internal_static_dataservices_SyncResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.data.DataServicesProto.internal_static_dataservices_SyncResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.data.SyncResponse.class, grpc.data.SyncResponse.Builder.class);
    }

    // Construct using grpc.data.SyncResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSlotsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (slotsBuilder_ == null) {
        slots_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        slotsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.data.DataServicesProto.internal_static_dataservices_SyncResponse_descriptor;
    }

    @java.lang.Override
    public grpc.data.SyncResponse getDefaultInstanceForType() {
      return grpc.data.SyncResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.data.SyncResponse build() {
      grpc.data.SyncResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.data.SyncResponse buildPartial() {
      grpc.data.SyncResponse result = new grpc.data.SyncResponse(this);
      int from_bitField0_ = bitField0_;
      if (slotsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          slots_ = java.util.Collections.unmodifiableList(slots_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.slots_ = slots_;
      } else {
        result.slots_ = slotsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.data.SyncResponse) {
        return mergeFrom((grpc.data.SyncResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.data.SyncResponse other) {
      if (other == grpc.data.SyncResponse.getDefaultInstance()) return this;
      if (slotsBuilder_ == null) {
        if (!other.slots_.isEmpty()) {
          if (slots_.isEmpty()) {
            slots_ = other.slots_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSlotsIsMutable();
            slots_.addAll(other.slots_);
          }
          onChanged();
        }
      } else {
        if (!other.slots_.isEmpty()) {
          if (slotsBuilder_.isEmpty()) {
            slotsBuilder_.dispose();
            slotsBuilder_ = null;
            slots_ = other.slots_;
            bitField0_ = (bitField0_ & ~0x00000001);
            slotsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSlotsFieldBuilder() : null;
          } else {
            slotsBuilder_.addAllMessages(other.slots_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.data.SyncResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.data.SyncResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<grpc.data.Slot> slots_ =
      java.util.Collections.emptyList();
    private void ensureSlotsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        slots_ = new java.util.ArrayList<grpc.data.Slot>(slots_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.data.Slot, grpc.data.Slot.Builder, grpc.data.SlotOrBuilder> slotsBuilder_;

    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public java.util.List<grpc.data.Slot> getSlotsList() {
      if (slotsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(slots_);
      } else {
        return slotsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public int getSlotsCount() {
      if (slotsBuilder_ == null) {
        return slots_.size();
      } else {
        return slotsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public grpc.data.Slot getSlots(int index) {
      if (slotsBuilder_ == null) {
        return slots_.get(index);
      } else {
        return slotsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public Builder setSlots(
        int index, grpc.data.Slot value) {
      if (slotsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSlotsIsMutable();
        slots_.set(index, value);
        onChanged();
      } else {
        slotsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public Builder setSlots(
        int index, grpc.data.Slot.Builder builderForValue) {
      if (slotsBuilder_ == null) {
        ensureSlotsIsMutable();
        slots_.set(index, builderForValue.build());
        onChanged();
      } else {
        slotsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public Builder addSlots(grpc.data.Slot value) {
      if (slotsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSlotsIsMutable();
        slots_.add(value);
        onChanged();
      } else {
        slotsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public Builder addSlots(
        int index, grpc.data.Slot value) {
      if (slotsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSlotsIsMutable();
        slots_.add(index, value);
        onChanged();
      } else {
        slotsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public Builder addSlots(
        grpc.data.Slot.Builder builderForValue) {
      if (slotsBuilder_ == null) {
        ensureSlotsIsMutable();
        slots_.add(builderForValue.build());
        onChanged();
      } else {
        slotsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public Builder addSlots(
        int index, grpc.data.Slot.Builder builderForValue) {
      if (slotsBuilder_ == null) {
        ensureSlotsIsMutable();
        slots_.add(index, builderForValue.build());
        onChanged();
      } else {
        slotsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public Builder addAllSlots(
        java.lang.Iterable<? extends grpc.data.Slot> values) {
      if (slotsBuilder_ == null) {
        ensureSlotsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, slots_);
        onChanged();
      } else {
        slotsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public Builder clearSlots() {
      if (slotsBuilder_ == null) {
        slots_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        slotsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public Builder removeSlots(int index) {
      if (slotsBuilder_ == null) {
        ensureSlotsIsMutable();
        slots_.remove(index);
        onChanged();
      } else {
        slotsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public grpc.data.Slot.Builder getSlotsBuilder(
        int index) {
      return getSlotsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public grpc.data.SlotOrBuilder getSlotsOrBuilder(
        int index) {
      if (slotsBuilder_ == null) {
        return slots_.get(index);  } else {
        return slotsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public java.util.List<? extends grpc.data.SlotOrBuilder> 
         getSlotsOrBuilderList() {
      if (slotsBuilder_ != null) {
        return slotsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(slots_);
      }
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public grpc.data.Slot.Builder addSlotsBuilder() {
      return getSlotsFieldBuilder().addBuilder(
          grpc.data.Slot.getDefaultInstance());
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public grpc.data.Slot.Builder addSlotsBuilder(
        int index) {
      return getSlotsFieldBuilder().addBuilder(
          index, grpc.data.Slot.getDefaultInstance());
    }
    /**
     * <code>repeated .dataservices.Slot slots = 1;</code>
     */
    public java.util.List<grpc.data.Slot.Builder> 
         getSlotsBuilderList() {
      return getSlotsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.data.Slot, grpc.data.Slot.Builder, grpc.data.SlotOrBuilder> 
        getSlotsFieldBuilder() {
      if (slotsBuilder_ == null) {
        slotsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.data.Slot, grpc.data.Slot.Builder, grpc.data.SlotOrBuilder>(
                slots_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        slots_ = null;
      }
      return slotsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dataservices.SyncResponse)
  }

  // @@protoc_insertion_point(class_scope:dataservices.SyncResponse)
  private static final grpc.data.SyncResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.data.SyncResponse();
  }

  public static grpc.data.SyncResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SyncResponse>
      PARSER = new com.google.protobuf.AbstractParser<SyncResponse>() {
    @java.lang.Override
    public SyncResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SyncResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SyncResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SyncResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.data.SyncResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

