// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataservices.proto

package grpc.data;

public interface TransferDataFromRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataservices.TransferDataFromRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 slot_id = 1;</code>
   * @return A list containing the slotId.
   */
  java.util.List<java.lang.Integer> getSlotIdList();
  /**
   * <code>repeated int32 slot_id = 1;</code>
   * @return The count of slotId.
   */
  int getSlotIdCount();
  /**
   * <code>repeated int32 slot_id = 1;</code>
   * @param index The index of the element to return.
   * @return The slotId at the given index.
   */
  int getSlotId(int index);
}
